### ISSUE TITLE
Color Palette Update

### ISSUE THREAD

**Issue by AmberLe** [namely/styleguide#142]
Please make the following updates to the color palette:

- [x] Add $blue-95: #12393f
- [x] Rename shades of blue to the new convention
- [x] Replace any instance of $blue-pastel with $blue-25
 
![styleguide_color](https://cloud.githubusercontent.com/assets/4756619/10056803/e22aafae-620a-11e5-89d9-eddc33ba23ff.png)

**Comment by jasonfellows** [comment]
https://github.com/namely/styleguide/pull/149
