### ISSUE TITLE
Static style guide

### ISSUE THREAD

**Issue by jasonfellows** [namely/styleguide#154]
Since we've changed all the names for the blue colors to use a brightness scale instead of words, we should update the styleguide specs.

**Comment by AmberLe** [comment]
Will do! I have a growing list:
- [ ] update with new names for blue colors
- [ ] use rems instead of px 
- [ ] icons: investigate svg export issue

**Comment by AmberLe** [comment]
Come and get it! 
https://basecamp.com/1899881/projects/666779/messages/29681611#comment_345402482
