### ISSUE TITLE
Design excluded and highlighted dates for ReactDatepicker

### ISSUE THREAD

**Issue by jasonfellows** [namely/styleguide#168]
We have the following design for datepicker already:

Can we add an appearance for days that have been excluded (unable to select)?

![screen shot 2015-09-18 at 5 47 55 pm](https://cloud.githubusercontent.com/assets/1119770/10368568/e321a1f2-6da3-11e5-8dc2-fc93887eccaa.png)

**Comment by jasonfellows** [comment]
We could optionally render a legend at the bottom if there are highlighted dates in the visible month.

(dot) = President's Day

**Comment by jasonfellows** [comment]
<img width="281" alt="screen shot 2015-10-14 at 12 08 38 pm" src="https://cloud.githubusercontent.com/assets/1119770/10489754/561684b2-726c-11e5-8629-b27fa39f3d12.png">

This is appearance I went with since this request was passed on. @AmberLe You ok with this in production?

**Comment by AmberLe** [comment]
Looks great @jasonfellows! Thank you!

**Comment by jasonfellows** [comment]
Hey, Ma! I'm a designer!
