### ISSUE TITLE
SimpleSelect: QA tasks

### ISSUE THREAD

**Issue by jasonfellows** [namely/styleguide#175]
In a wrapper object around SimpleSelect:

- [x] Field label as optional param
- [x] Support for props.extraClasses
- [x] Error handling

Further work needed on SimpleSelect:
- [x] Implement missing styles for SimpleSelect on a color background

**Comment by tsargent** [comment]
@jasonfellows I don't think the label should be a part of this, since other inputs (radio, checkbox, input fields) do not have components like this and will therefor not have a label.

**Comment by tsargent** [comment]
@jasonfellows also not sure about props.extraClasses.  The component should be styled correctly out of the box, and any styles that are needed for width, positioning, etc, could be handled in a containing element

**Comment by jasonfellows** [comment]
If you look at forms.js, that is how all the other form components are working. I think it's important that these all work in a uniform fashion so they can start saving us time by developing usage routine. You're actually passing in a prop named extraClasses already, but it isn't doing anything, resulting in this appearance when stacked with the other components.

<img width="814" alt="screen shot 2015-10-15 at 10 44 28 am" src="https://cloud.githubusercontent.com/assets/1119770/10517272/066e7924-732a-11e5-87f0-07090dc45ffc.png">

We can also add an empty function for default onChange to avoid throwing this error: 
<img width="420" alt="screen shot 2015-10-15 at 10 44 40 am" src="https://cloud.githubusercontent.com/assets/1119770/10517303/31ca5c32-732a-11e5-8346-04e59b7c2c83.png">
Adding a default in this way enables us to use React form elements with an old-school form submission, but still support passing in a custom event handler like this:
![screen shot 2015-10-15 at 10 44 50 am](https://cloud.githubusercontent.com/assets/1119770/10517333/50f06912-732a-11e5-9412-08b87471d363.png)

**Comment by tsargent** [comment]
I see.  I'll add the default function.

I think the extraClass is a little misleading here since this is not a single element like other inputs. Does it just attach to the `.simple-select` element, which is the top-most node?

**Comment by jasonfellows** [comment]
Yeah, the goal is to allow the use of a single component with the ability to make box model adjustments and other routine appearance tweaks. The most important case for passing in functional classes to a component seems to be adding margins, so they should be applied to the container node. UI builders should have just enough flexibility to use the component everywhere without having to alter it's code.

If someone has to add extra CSS to make it work for a design, either design has failed to work within the framework they've given us or we've failed to make the component adhere to the style guide. Staying on top of both is up to us.

Just noticed we need error handling on this component (and my datepicker too). I'll add that to the QA tasks.

**Comment by tsargent** [comment]
Error handling should be handled outside.  Again, it's just meant for appearance.  I have a prop for bordeColorClass, which is all we need to indicate that there's an error.

**Comment by jasonfellows** [comment]
![screen shot 2015-10-15 at 11 31 04 am](https://cloud.githubusercontent.com/assets/1119770/10518627/52020b16-7330-11e5-9700-f31ba694c22b.png)

Textual error feedback is 'inline' according to the style guide. I'd argue its better to handle errors as a state of the component. Errors passed in as props can be added to the state using getInitialState().

We have a lot of uses for form components that can offer immediate feedback on input errors. For example, a SSN field could use a regex that is checked onfocusout. If the input value doesn't fit the regex, we can display error state without ever needing to hit the server and wait for error to be passed down into props. This is a much better UX and lifts some load on our servers.

Since the errors are displayed so closely to the input it would also be difficult to display them and still allow altering of the component's box model by passing in extraClasses.

Why should we handle error feedback outside of the component?

**Comment by tsargent** [comment]
If we are going to use components for inputs that's fine.  We just need to all get on the same page.  The understanding so far has been that we're not creating components for inputs the way we did in the early React adoption.

**Comment by jasonfellows** [comment]
I that talk was more about avoiding components where we simply pass props
down to DOM node attributes 1:1. A fully-featured field component includes
the input, the label, the FieldError component, validation logic, etc.

On Thu, Oct 15, 2015 at 4:09 PM, Tyler Sargent <notifications@github.com>
wrote:

> If we are going to use components for inputs that's fine. We just need to
> all get on the same page. The understanding so far has been that we're not
> creating components for inputs the way we did in the early React adoption.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/namely/styleguide/issues/175#issuecomment-148506987>.
>



-- 
Jason Fellows
Lead Software Engineer @ Namely Inc.
195 Broadway, 15th FL
New York, NY 10007
540.560.3008

**Comment by tsargent** [comment]
It's time for a thumb war.

**Comment by HipsterBrown** [comment]
A Field component should be a higher-order component that wraps an input to handle the state logic around validation and whatever styling is involved with that. The input itself should be as stateless/"dumb" as possible.

**Comment by tsargent** [comment]
Agreed.  This component is just meant to act as the input, nothing more.  If we want to use a component to show errors:

```
<Whatever errors={this.props.errors}>
  <SimpleSelect />
</Whatever>
```

**Comment by jasonfellows** [comment]
https://github.com/namely/styleguide/pull/233

https://github.com/namely/styleguide/pull/241
