### ISSUE TITLE
Notification Patterns

### ISSUE THREAD

**Issue by keithpops** [namely/styleguide#179]
Design has enhanced this pattern. It falls out of the scope of esig so let's discuss the best approach for integrating this as a separate build.

https://github.com/namely/esig/issues/75

![68747470733a2f2f6168612d6174746163686d656e74732d70726f642e73332e616d617a6f6e6177732e636f6d2f6174746163686d656e74732f353634343933366438646133346535636165353236636562636534333534383336383363393439352f6f726967696e616c2e706e673f31343430353939303733](https://cloud.githubusercontent.com/assets/471842/10525331/262e9ce4-7352-11e5-9a42-f6794b542a18.png)

**Comment by jasonfellows** [comment]
I see a few Namely UI components in there (Tag, Icon, OverlayClick, Tooltip). The rest would be HRIS material.
